name: Deploying .NET to IIS on Azure Windows Server

on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.405
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal




# jobs:
#   build-dotnet-application:
#     name: Build .NET Application
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup dotnet
#         uses: actions/setup-dotnet@v3
#         with: 
#           dotnet-version: '6.0.405'
          

# needs: build
# steps:
#   - name: Upload a Build Artifact
#     uses: actions/upload-artifact@v3
#     with:
#       name: dotnetapp-devsecops-demo-${{github.run_number}}
#       path: dotnetapp
#       if-no-files-found: error


#       - name: Copy the Public Folder to Ubuntu
#           uses: /ssh-scp-deploy@v1.2.0
#           with:
#             local: 'dotnetapp/*'                                                 
#             remote: 'dotnetapp/'                                                
#             host: ${{secrets.HOST}}                                  
#             user: ${{secrets.USER}}
#             password: ${{secrets.PASSWORD}}
#             pre_upload: 
#             post_upload: 
#             ssh_options: 
#             scp_options: 

      # - name: Verify .NET Version
      #   run: .NET -version

      # - name: Download the Code
      #   uses: actions/checkout@v3

      # - name: Fix the Permissions of mvnw command
      #   run: chmod +x mvnw

      # - name: replace the REPALCETHISVALUEINGITHUBACTIONS in pom.xml with Build Number
      #   run: sed -i "s/REPALCETHISVALUEINGITHUBACTIONS/${{github.run_number}}/g" pom.xml

      # - name: Build the Code
      #   run: ./mvnw package

      # - name: Verify the Build is Created or Not
      #   run: ls -l target/*.war

      # - name: Upload Action Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name:.war
      #     path: target/dotnetapp-devsecops-demo-${{github.run_number}}.war
